### ISSUE TITLE
thread 'main' panicked at src/files.rs:131:14:

### ISSUE THREAD

**Issue by mooncoffee1** [davenicholson-xyz/wallheaven#1]
thread 'main' panicked at src/files.rs:131:14:
Unable to call external script: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thats the error i get once i run wallheaven with anything like -r -t --hot

**Comment by davenicholson-xyz** [comment]
My bad. Tried to load a default config file without checking it exists. You can create a config file and it will work however new release with fix will be available any minute now. Thanks for the heads up.
