### ISSUE TITLE
Error: try again later

### ISSUE THREAD

**Issue by bwl-andromeda** [davenicholson-xyz/wallheaven#4]
I tried configuring wallheaven and ran into the fact that when configuring the config and then calling the program "wallheaven --hot" I get an error: Error: try again later. I don't understand why this happens... The system I'm trying to do this on: Ubuntu 22.04 LTS

**Comment by davenicholson-xyz** [comment]
Does it work without a config file? That error meant there was a problem connecting to the wallhaven api.

**Comment by bwl-andromeda** [comment]
Yes, by the way, it does not work without a configuration file, although I inserted it into the config following the example in my config and even tried to insert my key through --api-key to get pictures, but unfortunately it did not work


I think this is due to the fact that ubuntu 22.04 does not allow even through gsettings to change the wallpaper and through feh...

**Comment by davenicholson-xyz** [comment]
Correct. I believe on Ubuntu you need to change the wallpaper with gsettings. 

`gsettings set org.gnome.desktop.background picture-uri file:///path/to/image.jpg` or `gsettings set org.gnome.desktop.background picture-uri-dark file:///path/to/image.jpg` if you are using dark mode.

**Comment by davenicholson-xyz** [comment]
Just tried it on an Ubuntu 22.04 VM and I'm having the same issue. One of the Rust libraries doesn't play well on Ubuntu. Going to work in a fix.

**Comment by davenicholson-xyz** [comment]
Have fixed the issue as of release `0.2.4`. Should work now once you've updated your install.

**Comment by bwl-andromeda** [comment]
Nice! This is work! Thanks for much!
